#Docker Compose Datei für die Einrichtung der PiHole Anwendungen

version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "8080:80"  # Lokaler Port 8080 wird auf den Containerport 80 gemappt
    volumes:
      - ./html:/usr/share/nginx/html
    restart: always

  pihole1:
    image: pihole/pihole:latest
    container_name: pihole-container-1
    hostname: pihole1
    environment:
      TZ: "Europe/Berlin"  # Zeitzone anpassen
      WEBPASSWORD: "Password123"  # Passwort für die Pi-hole-Weboberfläche
    volumes:
      - ./pihole/etc-pihole:/etc/pihole
      - ./pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "5356:53/tcp"  # DNS-Port (TCP)
      - "5356:53/udp"  # DNS-Port (UDP)
      - "8081:80"      # Pi-hole-Weboberfläche (http://localhost:8081/admin)
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

  pihole2:
    image: pihole/pihole:latest
    container_name: pihole-container-2
    hostname: pihole2
    environment:
      TZ: "Europe/Berlin" # Zeitzone anpassen
      WEBPASSWORD: "Password123" # Passwort für Webinterface
    volumes:
      - ./pihole2/etc-pihole:/etc/pihole
      - ./pihole2/etc-dnsmasq.d:/etc/dnsmasq.d
    ports:
      - "5355:53/tcp"
      - "5355:53/udp"
      - "8082:80" # Webinterface (http://localhost:8082/admin)

    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 8.8.4.4
    restart: unless-stopped

    
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-container
    ports:
      - "9000:9000"  # Webinterface von Portainer (http://localhost:9000)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Zugriff auf Docker
      - ./portainer-data:/data  # Persistente Daten von Portainer
    restart: always
